### ISSUE TITLE
Does expired recommendations gets automatically cleaned up from the db?

### ISSUE THREAD

**Issue by abejoe** [grahamjenson/hapiger#19]
I just wanted to know does expired recommendations gets automatically cleaned up form the database. In my use case, recommendations gets fed based on user activity. So I'm expecting recommendations will be fed in massive amounts. I have also set a two week expiry for recommendations. 

My concern is the presence of expired/redundant recommendations in the db. I have validated that expired recommendations does not affect the present recommendations but simply the presence of data in the db may affect the performance.  

Has removal of redundant data been automated or should I do it from my part?

**Comment by grahamjenson** [comment]
Hey,

The expired events will be removed when [Compacting](https://github.com/grahamjenson/hapiger#compacting-the-event-store). This will kick off a few database tasks making everything faster and should be done regularly.

**Comment by abejoe** [comment]
I have a few queries,
1) Is it possible to set the expiry along with the time? If so please show an example for the same.
2) How exactly does the numbering for 'like and dislike' works while getting recommendation?

**Comment by grahamjenson** [comment]
1. The last Example [here](https://github.com/grahamjenson/hapiger#create-some-events) shows how to set the expiry time
2. Hapiger uses [Cosign Similarity](https://en.wikipedia.org/wiki/Cosine_similarity) to determine the distance between recommendations

**Comment by abejoe** [comment]
The last example mentions expiry with date and by default, it get sets at 00:00:00 of that day. I would like to know if its possible to set the expiry date along with the 'time'?
