### ISSUE TITLE
link driver

### ISSUE THREAD

**Issue by thomasmodeneis** [grahamjenson/hapiger#7]
I'm doing a driver that maybe helpful for other people to be able to use hapiger with their nodejs apps
https://www.npmjs.com/package/hapigerjs

cheers

**Comment by grahamjenson** [comment]
Awesome :)

**Comment by thomasmodeneis** [comment]
pull https://github.com/grahamjenson/hapiger/pull/12 will close this one.

**Comment by grahamjenson** [comment]
Cheers.
